name: LifeSteal
version: '1.1-SNAPSHOT'
main: dev.zsrmat.lifeSteal.LifeSteal
api-version: '1.21'
authors: [ zsrmat ]
softdepend: [PlaceholderAPI]
description: A plugin that gives you 3 lives, if you lose them you get banned, if you kill you gain more lives.
commands:
  lifesteal:
    description: Show your lives or those of another player
    aliases: [ls]
    usage: /lifesteal [player]

